name: Check Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
